# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/workspace/lib/cqueue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/workspace/lib/cqueue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/workspace/lib/cqueue/CMakeFiles /data/workspace/lib/cqueue/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/workspace/lib/cqueue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clang-tidy

# Build rule for target.
clang-tidy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clang-tidy
.PHONY : clang-tidy

# fast build rule for target.
clang-tidy/fast:
	$(MAKE) -f CMakeFiles/clang-tidy.dir/build.make CMakeFiles/clang-tidy.dir/build
.PHONY : clang-tidy/fast

#=============================================================================
# Target rules for targets named cqueue

# Build rule for target.
cqueue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cqueue
.PHONY : cqueue

# fast build rule for target.
cqueue/fast:
	$(MAKE) -f CMakeFiles/cqueue.dir/build.make CMakeFiles/cqueue.dir/build
.PHONY : cqueue/fast

#=============================================================================
# Target rules for targets named cqueue_s

# Build rule for target.
cqueue_s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cqueue_s
.PHONY : cqueue_s

# fast build rule for target.
cqueue_s/fast:
	$(MAKE) -f CMakeFiles/cqueue_s.dir/build.make CMakeFiles/cqueue_s.dir/build
.PHONY : cqueue_s/fast

#=============================================================================
# Target rules for targets named benchmarks

# Build rule for target.
benchmarks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmarks
.PHONY : benchmarks

# fast build rule for target.
benchmarks/fast:
	$(MAKE) -f CMakeFiles/benchmarks.dir/build.make CMakeFiles/benchmarks.dir/build
.PHONY : benchmarks/fast

#=============================================================================
# Target rules for targets named cppcheck

# Build rule for target.
cppcheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cppcheck
.PHONY : cppcheck

# fast build rule for target.
cppcheck/fast:
	$(MAKE) -f CMakeFiles/cppcheck.dir/build.make CMakeFiles/cppcheck.dir/build
.PHONY : cppcheck/fast

#=============================================================================
# Target rules for targets named cqueue_objlib

# Build rule for target.
cqueue_objlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cqueue_objlib
.PHONY : cqueue_objlib

# fast build rule for target.
cqueue_objlib/fast:
	$(MAKE) -f CMakeFiles/cqueue_objlib.dir/build.make CMakeFiles/cqueue_objlib.dir/build
.PHONY : cqueue_objlib/fast

#=============================================================================
# Target rules for targets named test_ringqueue

# Build rule for target.
test_ringqueue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ringqueue
.PHONY : test_ringqueue

# fast build rule for target.
test_ringqueue/fast:
	$(MAKE) -f test/CMakeFiles/test_ringqueue.dir/build.make test/CMakeFiles/test_ringqueue.dir/build
.PHONY : test_ringqueue/fast

#=============================================================================
# Target rules for targets named testcqueue

# Build rule for target.
testcqueue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testcqueue
.PHONY : testcqueue

# fast build rule for target.
testcqueue/fast:
	$(MAKE) -f test/CMakeFiles/testcqueue.dir/build.make test/CMakeFiles/testcqueue.dir/build
.PHONY : testcqueue/fast

src/ringqueue.o: src/ringqueue.c.o

.PHONY : src/ringqueue.o

# target to build an object file
src/ringqueue.c.o:
	$(MAKE) -f CMakeFiles/cqueue_objlib.dir/build.make CMakeFiles/cqueue_objlib.dir/src/ringqueue.c.o
.PHONY : src/ringqueue.c.o

src/ringqueue.i: src/ringqueue.c.i

.PHONY : src/ringqueue.i

# target to preprocess a source file
src/ringqueue.c.i:
	$(MAKE) -f CMakeFiles/cqueue_objlib.dir/build.make CMakeFiles/cqueue_objlib.dir/src/ringqueue.c.i
.PHONY : src/ringqueue.c.i

src/ringqueue.s: src/ringqueue.c.s

.PHONY : src/ringqueue.s

# target to generate assembly for a file
src/ringqueue.c.s:
	$(MAKE) -f CMakeFiles/cqueue_objlib.dir/build.make CMakeFiles/cqueue_objlib.dir/src/ringqueue.c.s
.PHONY : src/ringqueue.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... clang-tidy"
	@echo "... cqueue"
	@echo "... test"
	@echo "... cqueue_s"
	@echo "... benchmarks"
	@echo "... cppcheck"
	@echo "... cqueue_objlib"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... test_ringqueue"
	@echo "... testcqueue"
	@echo "... src/ringqueue.o"
	@echo "... src/ringqueue.i"
	@echo "... src/ringqueue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

